// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SystemBase.Data;

#nullable disable

namespace SystemBase.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    [Migration("20260626151858_UpdateUsersImageUser2")]
    partial class UpdateUsersImageUser2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SystemBase.Models.Area", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("id");

                    b.ToTable("areas");

                    b.HasData(
                        new
                        {
                            id = 1,
                            code = "PROD",
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            name = "Producción"
                        },
                        new
                        {
                            id = 2,
                            code = "RH",
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            name = "Recursos Humanos"
                        },
                        new
                        {
                            id = 3,
                            code = "ALM",
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            name = "Almacén"
                        },
                        new
                        {
                            id = 4,
                            code = "LIMP",
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            name = "Limpieza"
                        });
                });

            modelBuilder.Entity("SystemBase.Models.Campus", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("code")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("direccion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("idCompany")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("id");

                    b.HasIndex("idCompany");

                    b.ToTable("campuses");

                    b.HasData(
                        new
                        {
                            id = 1,
                            code = 1,
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            direccion = "Carretera Puebla-Tlaxcala Km 5, Texmelucan, Pue.",
                            idCompany = 1,
                            name = "Matriz Principal Puebla"
                        });
                });

            modelBuilder.Entity("SystemBase.Models.CampusArea", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTimeOffset>("created")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("idArea")
                        .HasColumnType("int");

                    b.Property<int>("idCampus")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("idArea");

                    b.HasIndex("idCampus", "idArea")
                        .IsUnique();

                    b.ToTable("campusAreas");

                    b.HasData(
                        new
                        {
                            id = 1,
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idArea = 1,
                            idCampus = 1
                        },
                        new
                        {
                            id = 2,
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idArea = 2,
                            idCampus = 1
                        },
                        new
                        {
                            id = 3,
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idArea = 3,
                            idCampus = 1
                        },
                        new
                        {
                            id = 4,
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idArea = 4,
                            idCampus = 1
                        });
                });

            modelBuilder.Entity("SystemBase.Models.CampusAreaWorkShift", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTimeOffset>("created")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("idCampusArea")
                        .HasColumnType("int");

                    b.Property<int>("idWorkShift")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("idWorkShift");

                    b.HasIndex("idCampusArea", "idWorkShift")
                        .IsUnique();

                    b.ToTable("campusAreaWorkShifts");

                    b.HasData(
                        new
                        {
                            id = 1,
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idCampusArea = 1,
                            idWorkShift = 1
                        },
                        new
                        {
                            id = 2,
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idCampusArea = 1,
                            idWorkShift = 2
                        },
                        new
                        {
                            id = 3,
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idCampusArea = 3,
                            idWorkShift = 1
                        },
                        new
                        {
                            id = 4,
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idCampusArea = 3,
                            idWorkShift = 2
                        },
                        new
                        {
                            id = 5,
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idCampusArea = 4,
                            idWorkShift = 1
                        });
                });

            modelBuilder.Entity("SystemBase.Models.CampusAreaWorkShiftTeam", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTimeOffset>("created")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("idCampusAreaWorkShift")
                        .HasColumnType("int");

                    b.Property<int>("idTeam")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("idTeam");

                    b.HasIndex("idCampusAreaWorkShift", "idTeam")
                        .IsUnique();

                    b.ToTable("campusAreaWorkShiftTeams");

                    b.HasData(
                        new
                        {
                            id = 1,
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idCampusAreaWorkShift = 1,
                            idTeam = 1
                        },
                        new
                        {
                            id = 2,
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idCampusAreaWorkShift = 2,
                            idTeam = 1
                        },
                        new
                        {
                            id = 3,
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idCampusAreaWorkShift = 1,
                            idTeam = 2
                        },
                        new
                        {
                            id = 4,
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idCampusAreaWorkShift = 3,
                            idTeam = 3
                        },
                        new
                        {
                            id = 5,
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idCampusAreaWorkShift = 4,
                            idTeam = 3
                        },
                        new
                        {
                            id = 6,
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idCampusAreaWorkShift = 4,
                            idTeam = 4
                        },
                        new
                        {
                            id = 7,
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idCampusAreaWorkShift = 5,
                            idTeam = 5
                        });
                });

            modelBuilder.Entity("SystemBase.Models.Company", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTimeOffset>("created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("direccion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("id");

                    b.ToTable("companies");

                    b.HasData(
                        new
                        {
                            id = 1,
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            direccion = "Av. Independencia 200, Puebla, Pue.",
                            name = "Órbita 360"
                        });
                });

            modelBuilder.Entity("SystemBase.Models.EndpointAccessNameRule", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTimeOffset?>("deleteAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("idEndpointAccess")
                        .HasColumnType("int");

                    b.Property<int>("idNameRule")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("idEndpointAccess");

                    b.HasIndex("idNameRule");

                    b.ToTable("endpointAccessNameRules");

                    b.HasData(
                        new
                        {
                            id = 1,
                            idEndpointAccess = 1,
                            idNameRule = 1
                        },
                        new
                        {
                            id = 2,
                            idEndpointAccess = 3,
                            idNameRule = 1
                        },
                        new
                        {
                            id = 3,
                            idEndpointAccess = 6,
                            idNameRule = 1
                        },
                        new
                        {
                            id = 4,
                            idEndpointAccess = 10,
                            idNameRule = 1
                        },
                        new
                        {
                            id = 5,
                            idEndpointAccess = 11,
                            idNameRule = 1
                        },
                        new
                        {
                            id = 6,
                            idEndpointAccess = 14,
                            idNameRule = 1
                        },
                        new
                        {
                            id = 7,
                            idEndpointAccess = 15,
                            idNameRule = 1
                        },
                        new
                        {
                            id = 8,
                            idEndpointAccess = 16,
                            idNameRule = 1
                        },
                        new
                        {
                            id = 9,
                            idEndpointAccess = 17,
                            idNameRule = 1
                        },
                        new
                        {
                            id = 10,
                            idEndpointAccess = 18,
                            idNameRule = 1
                        },
                        new
                        {
                            id = 11,
                            idEndpointAccess = 20,
                            idNameRule = 1
                        },
                        new
                        {
                            id = 12,
                            idEndpointAccess = 23,
                            idNameRule = 1
                        },
                        new
                        {
                            id = 13,
                            idEndpointAccess = 1,
                            idNameRule = 2
                        },
                        new
                        {
                            id = 14,
                            idEndpointAccess = 3,
                            idNameRule = 2
                        },
                        new
                        {
                            id = 15,
                            idEndpointAccess = 6,
                            idNameRule = 2
                        },
                        new
                        {
                            id = 16,
                            idEndpointAccess = 10,
                            idNameRule = 2
                        },
                        new
                        {
                            id = 17,
                            idEndpointAccess = 11,
                            idNameRule = 2
                        },
                        new
                        {
                            id = 18,
                            idEndpointAccess = 14,
                            idNameRule = 2
                        },
                        new
                        {
                            id = 19,
                            idEndpointAccess = 15,
                            idNameRule = 2
                        },
                        new
                        {
                            id = 20,
                            idEndpointAccess = 16,
                            idNameRule = 2
                        },
                        new
                        {
                            id = 21,
                            idEndpointAccess = 17,
                            idNameRule = 2
                        },
                        new
                        {
                            id = 22,
                            idEndpointAccess = 18,
                            idNameRule = 2
                        },
                        new
                        {
                            id = 23,
                            idEndpointAccess = 20,
                            idNameRule = 2
                        },
                        new
                        {
                            id = 24,
                            idEndpointAccess = 23,
                            idNameRule = 2
                        },
                        new
                        {
                            id = 25,
                            idEndpointAccess = 2,
                            idNameRule = 3
                        },
                        new
                        {
                            id = 26,
                            idEndpointAccess = 4,
                            idNameRule = 3
                        },
                        new
                        {
                            id = 27,
                            idEndpointAccess = 7,
                            idNameRule = 3
                        },
                        new
                        {
                            id = 28,
                            idEndpointAccess = 9,
                            idNameRule = 3
                        },
                        new
                        {
                            id = 29,
                            idEndpointAccess = 13,
                            idNameRule = 3
                        },
                        new
                        {
                            id = 30,
                            idEndpointAccess = 22,
                            idNameRule = 3
                        },
                        new
                        {
                            id = 31,
                            idEndpointAccess = 19,
                            idNameRule = 3
                        },
                        new
                        {
                            id = 32,
                            idEndpointAccess = 2,
                            idNameRule = 4
                        },
                        new
                        {
                            id = 33,
                            idEndpointAccess = 4,
                            idNameRule = 4
                        },
                        new
                        {
                            id = 34,
                            idEndpointAccess = 7,
                            idNameRule = 4
                        },
                        new
                        {
                            id = 35,
                            idEndpointAccess = 9,
                            idNameRule = 4
                        },
                        new
                        {
                            id = 36,
                            idEndpointAccess = 12,
                            idNameRule = 4
                        },
                        new
                        {
                            id = 37,
                            idEndpointAccess = 21,
                            idNameRule = 4
                        },
                        new
                        {
                            id = 38,
                            idEndpointAccess = 19,
                            idNameRule = 4
                        },
                        new
                        {
                            id = 39,
                            idEndpointAccess = 24,
                            idNameRule = 5
                        },
                        new
                        {
                            id = 40,
                            idEndpointAccess = 25,
                            idNameRule = 5
                        },
                        new
                        {
                            id = 41,
                            idEndpointAccess = 5,
                            idNameRule = 5
                        },
                        new
                        {
                            id = 42,
                            idEndpointAccess = 8,
                            idNameRule = 5
                        },
                        new
                        {
                            id = 43,
                            idEndpointAccess = 12,
                            idNameRule = 5
                        },
                        new
                        {
                            id = 44,
                            idEndpointAccess = 21,
                            idNameRule = 5
                        },
                        new
                        {
                            id = 45,
                            idEndpointAccess = 19,
                            idNameRule = 5
                        });
                });

            modelBuilder.Entity("SystemBase.Models.NameRule", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTimeOffset?>("deleteAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.ToTable("nameRules");

                    b.HasData(
                        new
                        {
                            id = 1,
                            name = "Acceso de CEO"
                        },
                        new
                        {
                            id = 2,
                            name = "Accesos de Gerente N-1"
                        },
                        new
                        {
                            id = 3,
                            name = "Accesos de Supervisor"
                        },
                        new
                        {
                            id = 4,
                            name = "Accesos de Coordinador"
                        },
                        new
                        {
                            id = 5,
                            name = "Accesos de Empleado"
                        });
                });

            modelBuilder.Entity("SystemBase.Models.ProfileAccess", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("canRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("canWrite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("idRole")
                        .HasColumnType("int");

                    b.Property<string>("profileTable")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("id");

                    b.HasIndex("idRole", "profileTable")
                        .IsUnique();

                    b.ToTable("profileAccess");
                });

            modelBuilder.Entity("SystemBase.Models.Roles", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("code")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("created")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("deleteAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("idNameRule")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.HasIndex("idNameRule");

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            id = 1,
                            code = 1,
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idNameRule = 1,
                            name = "CEO"
                        },
                        new
                        {
                            id = 2,
                            code = 2,
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idNameRule = 2,
                            name = "Gerente General"
                        },
                        new
                        {
                            id = 3,
                            code = 2,
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idNameRule = 2,
                            name = "Gerente RH"
                        },
                        new
                        {
                            id = 4,
                            code = 3,
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idNameRule = 3,
                            name = "Supervisor"
                        },
                        new
                        {
                            id = 5,
                            code = 4,
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idNameRule = 4,
                            name = "Coordinador"
                        },
                        new
                        {
                            id = 6,
                            code = 5,
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idNameRule = 5,
                            name = "Operador de producción"
                        },
                        new
                        {
                            id = 7,
                            code = 5,
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idNameRule = 5,
                            name = "Auxiliar de almacén"
                        },
                        new
                        {
                            id = 8,
                            code = 5,
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idNameRule = 5,
                            name = "Personal de limpieza industrial"
                        });
                });

            modelBuilder.Entity("SystemBase.Models.Team", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTimeOffset>("created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("id");

                    b.ToTable("teams");

                    b.HasData(
                        new
                        {
                            id = 1,
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            name = "PROD-A1"
                        },
                        new
                        {
                            id = 2,
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            name = "PROD-A2"
                        },
                        new
                        {
                            id = 3,
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            name = "ALM-A1"
                        },
                        new
                        {
                            id = 4,
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            name = "ALM-A2"
                        },
                        new
                        {
                            id = 5,
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            name = "LIMP-A1"
                        });
                });

            modelBuilder.Entity("SystemBase.Models.UserAssignments", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("codeEmployee")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTimeOffset>("created")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("deleteAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("idRole")
                        .HasColumnType("int");

                    b.Property<int>("idUser")
                        .HasColumnType("int");

                    b.Property<bool>("isActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("scopeId")
                        .HasColumnType("int");

                    b.Property<string>("scopeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("id");

                    b.HasIndex("idRole");

                    b.HasIndex("idUser");

                    b.HasIndex("scopeId", "scopeType", "idUser", "idRole")
                        .IsUnique()
                        .HasFilter("[scopeId] IS NOT NULL");

                    b.ToTable("userAssignments");

                    b.HasData(
                        new
                        {
                            id = 1,
                            codeEmployee = "CEO-01",
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idRole = 1,
                            idUser = 1,
                            isActive = true,
                            scopeId = 1,
                            scopeType = "company"
                        },
                        new
                        {
                            id = 2,
                            codeEmployee = "GG-01",
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idRole = 2,
                            idUser = 2,
                            isActive = true,
                            scopeId = 1,
                            scopeType = "campus"
                        },
                        new
                        {
                            id = 3,
                            codeEmployee = "GG-02",
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idRole = 2,
                            idUser = 3,
                            isActive = true,
                            scopeId = 1,
                            scopeType = "campus"
                        },
                        new
                        {
                            id = 4,
                            codeEmployee = "GRH-01",
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idRole = 3,
                            idUser = 4,
                            isActive = true,
                            scopeId = 2,
                            scopeType = "campus_area"
                        },
                        new
                        {
                            id = 5,
                            codeEmployee = "SUP-01",
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idRole = 4,
                            idUser = 5,
                            isActive = true,
                            scopeId = 3,
                            scopeType = "campus_area"
                        },
                        new
                        {
                            id = 6,
                            codeEmployee = "SUP-02",
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idRole = 4,
                            idUser = 6,
                            isActive = true,
                            scopeId = 4,
                            scopeType = "campus_area"
                        },
                        new
                        {
                            id = 7,
                            codeEmployee = "COORD-01",
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idRole = 5,
                            idUser = 7,
                            isActive = true,
                            scopeId = 1,
                            scopeType = "team"
                        },
                        new
                        {
                            id = 19,
                            codeEmployee = "COORD-01",
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idRole = 5,
                            idUser = 7,
                            isActive = true,
                            scopeId = 2,
                            scopeType = "team"
                        },
                        new
                        {
                            id = 20,
                            codeEmployee = "COORD-01",
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idRole = 5,
                            idUser = 7,
                            isActive = true,
                            scopeId = 3,
                            scopeType = "team"
                        },
                        new
                        {
                            id = 8,
                            codeEmployee = "COORD-02",
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idRole = 5,
                            idUser = 8,
                            isActive = true,
                            scopeId = 4,
                            scopeType = "team"
                        },
                        new
                        {
                            id = 21,
                            codeEmployee = "COORD-02",
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idRole = 5,
                            idUser = 8,
                            isActive = true,
                            scopeId = 5,
                            scopeType = "team"
                        },
                        new
                        {
                            id = 22,
                            codeEmployee = "COORD-02",
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idRole = 5,
                            idUser = 8,
                            isActive = true,
                            scopeId = 6,
                            scopeType = "team"
                        },
                        new
                        {
                            id = 23,
                            codeEmployee = "COORD-02",
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idRole = 5,
                            idUser = 8,
                            isActive = true,
                            scopeId = 7,
                            scopeType = "team"
                        },
                        new
                        {
                            id = 10,
                            codeEmployee = "OP-01",
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idRole = 6,
                            idUser = 10,
                            isActive = true,
                            scopeId = 1,
                            scopeType = "team"
                        },
                        new
                        {
                            id = 11,
                            codeEmployee = "OP-02",
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idRole = 6,
                            idUser = 11,
                            isActive = true,
                            scopeId = 2,
                            scopeType = "team"
                        },
                        new
                        {
                            id = 14,
                            codeEmployee = "OP-03",
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idRole = 6,
                            idUser = 14,
                            isActive = true,
                            scopeId = 3,
                            scopeType = "team"
                        },
                        new
                        {
                            id = 12,
                            codeEmployee = "ALM-01",
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idRole = 7,
                            idUser = 12,
                            isActive = true,
                            scopeId = 4,
                            scopeType = "team"
                        },
                        new
                        {
                            id = 15,
                            codeEmployee = "ALM-02",
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idRole = 7,
                            idUser = 15,
                            isActive = true,
                            scopeId = 5,
                            scopeType = "team"
                        },
                        new
                        {
                            id = 16,
                            codeEmployee = "ALM-03",
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idRole = 7,
                            idUser = 16,
                            isActive = true,
                            scopeId = 6,
                            scopeType = "team"
                        },
                        new
                        {
                            id = 13,
                            codeEmployee = "LIMP-01",
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idRole = 8,
                            idUser = 13,
                            isActive = true,
                            scopeId = 7,
                            scopeType = "team"
                        },
                        new
                        {
                            id = 17,
                            codeEmployee = "LIMP-02",
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idRole = 8,
                            idUser = 17,
                            isActive = true,
                            scopeId = 7,
                            scopeType = "team"
                        },
                        new
                        {
                            id = 18,
                            codeEmployee = "LIMP-03",
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idRole = 8,
                            idUser = 18,
                            isActive = true,
                            scopeId = 7,
                            scopeType = "team"
                        });
                });

            modelBuilder.Entity("SystemBase.Models.Users", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("apm")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("app")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("created")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("deleteAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("imageUser")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("id");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            id = 1,
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            imageUser = "/profile/loise.png",
                            name = "Lois",
                            password = "$argon2id$v=19$m=32768,t=3,p=2$jFoauMd2iyzmYVYR1yQC8w$KMom+RiC97S1me2l5U5pZO7QXPLWpVeH53q+73zGbbc",
                            userName = "lois@orbita360.com"
                        },
                        new
                        {
                            id = 2,
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            name = "Hal",
                            password = "$argon2id$v=19$m=32768,t=3,p=2$M15qHjlWPTFjdgJYWzyZmg$0A23QPXTVCwpLyZA9L2gJQQzhQlHPfp4WdEiO9NsuSI",
                            userName = "@hal"
                        },
                        new
                        {
                            id = 3,
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            name = "Francis",
                            password = "$argon2id$v=19$m=32768,t=3,p=2$AaJAzWnR/ARKgCDsx4cUbA$PWHt/nBuwALS6wDluuRSp7tODe54iMbI5WkePZfotmg",
                            userName = "@francis"
                        },
                        new
                        {
                            id = 4,
                            app = "Feldspar",
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            imageUser = "/profile/craig.png",
                            name = "Craig",
                            password = "$argon2id$v=19$m=32768,t=3,p=2$irVbxPe3LVHpvkaWmTZOYg$r5XxgeJCGnzBdZtoiGwiocBaJG22spKKbfqyvduRQC0",
                            userName = "@craig"
                        },
                        new
                        {
                            id = 5,
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            name = "Malcolm",
                            password = "$argon2id$v=19$m=32768,t=3,p=2$d+mEkp8CSO+u3CU3ee/wWw$TIswvT+LV5NAtf1XmX9TokpY5Gd3dUcQqLy8UyQKt2Q",
                            userName = "@malcolm"
                        },
                        new
                        {
                            id = 6,
                            app = "Kenarban",
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            imageUser = "/profile/steve.png",
                            name = "Stevie",
                            password = "$argon2id$v=19$m=32768,t=3,p=2$hQLHjkb5/+2atRhTramqHQ$uP0CxGQZETrg33ryKGe83uF9IEtBfMw6StDJGZi+zf4",
                            userName = "@stevie"
                        },
                        new
                        {
                            id = 7,
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            imageUser = "/profile/reese.png",
                            name = "Reese",
                            password = "$argon2id$v=19$m=32768,t=3,p=2$gA9TEt+xSSCUD1Xmsub/PA$n3tF52M2pT4/GNFHBu0+zvZfv53DaOQXGJZfUBLbo9c",
                            userName = "@reese"
                        },
                        new
                        {
                            id = 8,
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            name = "Dewey",
                            password = "$argon2id$v=19$m=32768,t=3,p=2$pYidoMRHGfHZ+3KdvG7yZg$N8zm2Y/sLaRYwsWVsySGCGa6qQM6XU80e1rMs+yVpGU",
                            userName = "@dewey"
                        },
                        new
                        {
                            id = 10,
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            name = "Lloyd",
                            password = "$argon2id$v=19$m=32768,t=3,p=2$JGizOXk7Qh0QY+m42LhZbQ$Sr0P/Dlz4GihxeHJbpO+I8qjyYXain6CsqgnvnrbSeE",
                            userName = "@lloyd"
                        },
                        new
                        {
                            id = 11,
                            app = "Hooper",
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            name = "Dabney",
                            password = "$argon2id$v=19$m=32768,t=3,p=2$KXhY+6UIP7dpFSyXVRdZtA$JV8+JbE6F54KwT+2O2y9QRD0fWwahbRkQFaJqQnJ7Cs",
                            userName = "@dabney"
                        },
                        new
                        {
                            id = 12,
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            name = "Kevin",
                            password = "$argon2id$v=19$m=32768,t=3,p=2$GWrRaFaLxJmccVMYfQ7wUA$mgiNR02Z3Tl0ktarOSs2IfAZVfgF1S+hJY0j2gn/+V8",
                            userName = "@kevin"
                        },
                        new
                        {
                            id = 13,
                            app = "Sanders",
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            name = "Cynthia",
                            password = "$argon2id$v=19$m=32768,t=3,p=2$z9DxaKEgMicMtmqyaZ44vg$z3cjb0WN7ryRvUoLdlgpX2ut4NCPPvjji66eyGyKB3w",
                            userName = "@cynthia"
                        },
                        new
                        {
                            id = 14,
                            app = "Hanson",
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            name = "David",
                            password = "$argon2id$v=19$m=32768,t=3,p=2$4e5VBKvaB7XMivJGGrAxGw$e9NyHp4eT+Le1IUPDyveOMI1B+JlMddS704BqxCEJzI",
                            userName = "@davidh"
                        },
                        new
                        {
                            id = 15,
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            name = "Chad",
                            password = "$argon2id$v=19$m=32768,t=3,p=2$f6YGp70U1OU8RcuKwfBCFQ$JD/BhjhWguU7YmRq8BRFtSpH7ohtVcu1NdjQ1yATIzk",
                            userName = "@chad"
                        },
                        new
                        {
                            id = 16,
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            name = "Davey",
                            password = "$argon2id$v=19$m=32768,t=3,p=2$JPzg8Gi8jaA8SGjLhvg7jw$IW/ju7XHIjlZwYcZTsFpYoWqvqXkJEMbAQU0e775r8o",
                            userName = "@davey"
                        },
                        new
                        {
                            id = 17,
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            name = "Zoe",
                            password = "$argon2id$v=19$m=32768,t=3,p=2$P5BXyIA7dNaM2RiHCo6UZA$Fzi30u1fOIJ1JwPv3ekbkjE4BT/LlSyL/7U9aP56Jrs",
                            userName = "@zoe"
                        },
                        new
                        {
                            id = 18,
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            name = "Penelope",
                            password = "$argon2id$v=19$m=32768,t=3,p=2$mI+T/1JbTFrWc9HZyD5YtQ$5BmyEI61rPSBU2w0mQpZxW759A2kJb+uMLv8+Ln8Fl4",
                            userName = "@penelope"
                        });
                });

            modelBuilder.Entity("SystemBase.Models.WorkShift", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTimeOffset>("created")
                        .HasColumnType("datetimeoffset");

                    b.Property<TimeOnly>("hourEnd")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("hourInit")
                        .HasColumnType("time");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("id");

                    b.ToTable("workShifts");

                    b.HasData(
                        new
                        {
                            id = 1,
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            hourEnd = new TimeOnly(14, 0, 0),
                            hourInit = new TimeOnly(6, 0, 0),
                            name = "Mañana"
                        },
                        new
                        {
                            id = 2,
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            hourEnd = new TimeOnly(22, 0, 0),
                            hourInit = new TimeOnly(14, 0, 0),
                            name = "Tarde"
                        });
                });

            modelBuilder.Entity("SystemBase.Models.endpointAccess", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTimeOffset?>("deleteAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("endpoint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("method")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("permission")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.ToTable("endpointAccess");

                    b.HasData(
                        new
                        {
                            id = 1,
                            endpoint = "/auth/logout",
                            method = "POST",
                            permission = "auth.logout.*",
                            status = true
                        },
                        new
                        {
                            id = 2,
                            endpoint = "/auth/logout",
                            method = "POST",
                            permission = "auth.logout.subordinate",
                            status = true
                        },
                        new
                        {
                            id = 3,
                            endpoint = "/auth/access",
                            method = "GET",
                            permission = "auth.access.*",
                            status = true
                        },
                        new
                        {
                            id = 4,
                            endpoint = "/auth/access",
                            method = "GET",
                            permission = "auth.access.subordinate",
                            status = true
                        },
                        new
                        {
                            id = 5,
                            endpoint = "/user",
                            method = "GET",
                            permission = "users.read.self",
                            status = true
                        },
                        new
                        {
                            id = 6,
                            endpoint = "/user",
                            method = "GET",
                            permission = "users.read.*",
                            status = true
                        },
                        new
                        {
                            id = 7,
                            endpoint = "/user",
                            method = "GET",
                            permission = "users.read.subordinate",
                            status = true
                        },
                        new
                        {
                            id = 8,
                            endpoint = "/user/{id}",
                            method = "GET",
                            permission = "users.read.self",
                            status = true
                        },
                        new
                        {
                            id = 9,
                            endpoint = "/user/{id}",
                            method = "GET",
                            permission = "users.read.subordinate",
                            status = true
                        },
                        new
                        {
                            id = 10,
                            endpoint = "/user/{id}",
                            method = "GET",
                            permission = "users.read.*",
                            status = true
                        },
                        new
                        {
                            id = 11,
                            endpoint = "/user",
                            method = "POST",
                            permission = "users.create.*",
                            status = true
                        },
                        new
                        {
                            id = 12,
                            endpoint = "/user/{id}",
                            method = "PUT",
                            permission = "users.update.self",
                            status = true
                        },
                        new
                        {
                            id = 13,
                            endpoint = "/user/{id}",
                            method = "PUT",
                            permission = "users.update.subordinate",
                            status = true
                        },
                        new
                        {
                            id = 14,
                            endpoint = "/user/{id}",
                            method = "PUT",
                            permission = "users.update.*",
                            status = true
                        },
                        new
                        {
                            id = 15,
                            endpoint = "/user/{id}",
                            method = "DELETE",
                            permission = "users.delete.*",
                            status = true
                        },
                        new
                        {
                            id = 16,
                            endpoint = "/user/{id}/status",
                            method = "PATCH",
                            permission = "users.status.*",
                            status = true
                        },
                        new
                        {
                            id = 17,
                            endpoint = "/user/{id}/assignment",
                            method = "POST",
                            permission = "users.assignment.create.*",
                            status = true
                        },
                        new
                        {
                            id = 18,
                            endpoint = "/user/{id}/assignment/{assignmentId}",
                            method = "DELETE",
                            permission = "users.assignment.delete.*",
                            status = true
                        },
                        new
                        {
                            id = 19,
                            endpoint = "/user/{id}/password",
                            method = "PUT",
                            permission = "users.password.self",
                            status = true
                        },
                        new
                        {
                            id = 20,
                            endpoint = "/user/{id}/password",
                            method = "PUT",
                            permission = "users.password.*",
                            status = true
                        },
                        new
                        {
                            id = 21,
                            endpoint = "/user/{id}/assignments",
                            method = "GET",
                            permission = "users.assignment.read.self",
                            status = true
                        },
                        new
                        {
                            id = 22,
                            endpoint = "/user/{id}/assignments",
                            method = "GET",
                            permission = "users.assignment.read.subordinate",
                            status = true
                        },
                        new
                        {
                            id = 23,
                            endpoint = "/user/{id}/assignments",
                            method = "GET",
                            permission = "users.assignment.read.*",
                            status = true
                        },
                        new
                        {
                            id = 24,
                            endpoint = "/auth/logout",
                            method = "POST",
                            permission = "auth.logout.self",
                            status = true
                        },
                        new
                        {
                            id = 25,
                            endpoint = "/auth/access",
                            method = "GET",
                            permission = "auth.access.self",
                            status = true
                        });
                });

            modelBuilder.Entity("SystemBase.Models.refreshTokens", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTimeOffset>("SessionExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("agentUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("createdAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("expiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("idUser")
                        .HasColumnType("int");

                    b.Property<string>("ipAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("tokenHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("idUser");

                    b.ToTable("refreshTokens");
                });

            modelBuilder.Entity("SystemBase.Models.Campus", b =>
                {
                    b.HasOne("SystemBase.Models.Company", "company")
                        .WithMany()
                        .HasForeignKey("idCompany")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("company");
                });

            modelBuilder.Entity("SystemBase.Models.CampusArea", b =>
                {
                    b.HasOne("SystemBase.Models.Area", "area")
                        .WithMany()
                        .HasForeignKey("idArea")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SystemBase.Models.Campus", "campus")
                        .WithMany()
                        .HasForeignKey("idCampus")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("area");

                    b.Navigation("campus");
                });

            modelBuilder.Entity("SystemBase.Models.CampusAreaWorkShift", b =>
                {
                    b.HasOne("SystemBase.Models.CampusArea", "campusArea")
                        .WithMany()
                        .HasForeignKey("idCampusArea")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SystemBase.Models.WorkShift", "workShift")
                        .WithMany()
                        .HasForeignKey("idWorkShift")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("campusArea");

                    b.Navigation("workShift");
                });

            modelBuilder.Entity("SystemBase.Models.CampusAreaWorkShiftTeam", b =>
                {
                    b.HasOne("SystemBase.Models.CampusAreaWorkShift", "campusAreaWorkShift")
                        .WithMany()
                        .HasForeignKey("idCampusAreaWorkShift")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SystemBase.Models.Team", "team")
                        .WithMany()
                        .HasForeignKey("idTeam")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("campusAreaWorkShift");

                    b.Navigation("team");
                });

            modelBuilder.Entity("SystemBase.Models.EndpointAccessNameRule", b =>
                {
                    b.HasOne("SystemBase.Models.endpointAccess", "endpointAccess")
                        .WithMany("endpointAccessNameRules")
                        .HasForeignKey("idEndpointAccess")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SystemBase.Models.NameRule", "nameRule")
                        .WithMany("endpointAccessNameRules")
                        .HasForeignKey("idNameRule")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("endpointAccess");

                    b.Navigation("nameRule");
                });

            modelBuilder.Entity("SystemBase.Models.ProfileAccess", b =>
                {
                    b.HasOne("SystemBase.Models.Roles", "roles")
                        .WithMany()
                        .HasForeignKey("idRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("roles");
                });

            modelBuilder.Entity("SystemBase.Models.Roles", b =>
                {
                    b.HasOne("SystemBase.Models.NameRule", "nameRule")
                        .WithMany("roles")
                        .HasForeignKey("idNameRule");

                    b.Navigation("nameRule");
                });

            modelBuilder.Entity("SystemBase.Models.UserAssignments", b =>
                {
                    b.HasOne("SystemBase.Models.Roles", "roles")
                        .WithMany()
                        .HasForeignKey("idRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SystemBase.Models.Users", "users")
                        .WithMany()
                        .HasForeignKey("idUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("roles");

                    b.Navigation("users");
                });

            modelBuilder.Entity("SystemBase.Models.refreshTokens", b =>
                {
                    b.HasOne("SystemBase.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("idUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SystemBase.Models.NameRule", b =>
                {
                    b.Navigation("endpointAccessNameRules");

                    b.Navigation("roles");
                });

            modelBuilder.Entity("SystemBase.Models.endpointAccess", b =>
                {
                    b.Navigation("endpointAccessNameRules");
                });
#pragma warning restore 612, 618
        }
    }
}
