// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SystemBase.Data;

#nullable disable

namespace SystemBase.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    [Migration("20260625193029_RenameScopeTypeCompanyToCampus")]
    partial class RenameScopeTypeCompanyToCampus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SystemBase.Models.Area", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("id");

                    b.ToTable("areas");
                });

            modelBuilder.Entity("SystemBase.Models.Campus", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("code")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("direccion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("idCompany")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("id");

                    b.HasIndex("idCompany");

                    b.ToTable("campuses");
                });

            modelBuilder.Entity("SystemBase.Models.CampusArea", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTimeOffset>("created")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("idArea")
                        .HasColumnType("int");

                    b.Property<int>("idCampus")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("idArea");

                    b.HasIndex("idCampus", "idArea")
                        .IsUnique();

                    b.ToTable("campusAreas");
                });

            modelBuilder.Entity("SystemBase.Models.CampusAreaWorkShift", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTimeOffset>("created")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("idCampusArea")
                        .HasColumnType("int");

                    b.Property<int>("idWorkShift")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("idWorkShift");

                    b.HasIndex("idCampusArea", "idWorkShift")
                        .IsUnique();

                    b.ToTable("campusAreaWorkShifts");
                });

            modelBuilder.Entity("SystemBase.Models.CampusAreaWorkShiftTeam", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTimeOffset>("created")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("idCampusAreaWorkShift")
                        .HasColumnType("int");

                    b.Property<int>("idTeam")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("idTeam");

                    b.HasIndex("idCampusAreaWorkShift", "idTeam")
                        .IsUnique();

                    b.ToTable("campusAreaWorkShiftTeams");
                });

            modelBuilder.Entity("SystemBase.Models.Company", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTimeOffset>("created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("direccion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("id");

                    b.ToTable("companies");
                });

            modelBuilder.Entity("SystemBase.Models.EndpointAccessNameRule", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTimeOffset?>("deleteAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("idEndpointAccess")
                        .HasColumnType("int");

                    b.Property<int>("idNameRule")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("idEndpointAccess");

                    b.HasIndex("idNameRule");

                    b.ToTable("endpointAccessNameRules");

                    b.HasData(
                        new
                        {
                            id = 1,
                            idEndpointAccess = 1,
                            idNameRule = 1
                        },
                        new
                        {
                            id = 2,
                            idEndpointAccess = 3,
                            idNameRule = 1
                        },
                        new
                        {
                            id = 3,
                            idEndpointAccess = 6,
                            idNameRule = 1
                        },
                        new
                        {
                            id = 4,
                            idEndpointAccess = 10,
                            idNameRule = 1
                        },
                        new
                        {
                            id = 5,
                            idEndpointAccess = 11,
                            idNameRule = 1
                        },
                        new
                        {
                            id = 6,
                            idEndpointAccess = 14,
                            idNameRule = 1
                        },
                        new
                        {
                            id = 7,
                            idEndpointAccess = 15,
                            idNameRule = 1
                        },
                        new
                        {
                            id = 8,
                            idEndpointAccess = 16,
                            idNameRule = 1
                        },
                        new
                        {
                            id = 9,
                            idEndpointAccess = 17,
                            idNameRule = 1
                        },
                        new
                        {
                            id = 10,
                            idEndpointAccess = 18,
                            idNameRule = 1
                        },
                        new
                        {
                            id = 11,
                            idEndpointAccess = 20,
                            idNameRule = 1
                        },
                        new
                        {
                            id = 12,
                            idEndpointAccess = 23,
                            idNameRule = 1
                        },
                        new
                        {
                            id = 13,
                            idEndpointAccess = 1,
                            idNameRule = 2
                        },
                        new
                        {
                            id = 14,
                            idEndpointAccess = 3,
                            idNameRule = 2
                        },
                        new
                        {
                            id = 15,
                            idEndpointAccess = 6,
                            idNameRule = 2
                        },
                        new
                        {
                            id = 16,
                            idEndpointAccess = 10,
                            idNameRule = 2
                        },
                        new
                        {
                            id = 17,
                            idEndpointAccess = 11,
                            idNameRule = 2
                        },
                        new
                        {
                            id = 18,
                            idEndpointAccess = 14,
                            idNameRule = 2
                        },
                        new
                        {
                            id = 19,
                            idEndpointAccess = 15,
                            idNameRule = 2
                        },
                        new
                        {
                            id = 20,
                            idEndpointAccess = 16,
                            idNameRule = 2
                        },
                        new
                        {
                            id = 21,
                            idEndpointAccess = 17,
                            idNameRule = 2
                        },
                        new
                        {
                            id = 22,
                            idEndpointAccess = 18,
                            idNameRule = 2
                        },
                        new
                        {
                            id = 23,
                            idEndpointAccess = 20,
                            idNameRule = 2
                        },
                        new
                        {
                            id = 24,
                            idEndpointAccess = 23,
                            idNameRule = 2
                        },
                        new
                        {
                            id = 25,
                            idEndpointAccess = 2,
                            idNameRule = 3
                        },
                        new
                        {
                            id = 26,
                            idEndpointAccess = 4,
                            idNameRule = 3
                        },
                        new
                        {
                            id = 27,
                            idEndpointAccess = 7,
                            idNameRule = 3
                        },
                        new
                        {
                            id = 28,
                            idEndpointAccess = 9,
                            idNameRule = 3
                        },
                        new
                        {
                            id = 29,
                            idEndpointAccess = 13,
                            idNameRule = 3
                        },
                        new
                        {
                            id = 30,
                            idEndpointAccess = 22,
                            idNameRule = 3
                        },
                        new
                        {
                            id = 31,
                            idEndpointAccess = 19,
                            idNameRule = 3
                        },
                        new
                        {
                            id = 32,
                            idEndpointAccess = 2,
                            idNameRule = 4
                        },
                        new
                        {
                            id = 33,
                            idEndpointAccess = 4,
                            idNameRule = 4
                        },
                        new
                        {
                            id = 34,
                            idEndpointAccess = 7,
                            idNameRule = 4
                        },
                        new
                        {
                            id = 35,
                            idEndpointAccess = 9,
                            idNameRule = 4
                        },
                        new
                        {
                            id = 36,
                            idEndpointAccess = 12,
                            idNameRule = 4
                        },
                        new
                        {
                            id = 37,
                            idEndpointAccess = 21,
                            idNameRule = 4
                        },
                        new
                        {
                            id = 38,
                            idEndpointAccess = 19,
                            idNameRule = 4
                        },
                        new
                        {
                            id = 39,
                            idEndpointAccess = 24,
                            idNameRule = 5
                        },
                        new
                        {
                            id = 40,
                            idEndpointAccess = 25,
                            idNameRule = 5
                        },
                        new
                        {
                            id = 41,
                            idEndpointAccess = 5,
                            idNameRule = 5
                        },
                        new
                        {
                            id = 42,
                            idEndpointAccess = 8,
                            idNameRule = 5
                        },
                        new
                        {
                            id = 43,
                            idEndpointAccess = 12,
                            idNameRule = 5
                        },
                        new
                        {
                            id = 44,
                            idEndpointAccess = 21,
                            idNameRule = 5
                        },
                        new
                        {
                            id = 45,
                            idEndpointAccess = 19,
                            idNameRule = 5
                        });
                });

            modelBuilder.Entity("SystemBase.Models.NameRule", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTimeOffset?>("deleteAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.ToTable("nameRules");

                    b.HasData(
                        new
                        {
                            id = 1,
                            name = "Acceso de CEO"
                        },
                        new
                        {
                            id = 2,
                            name = "Accesos de Gerente N-1"
                        },
                        new
                        {
                            id = 3,
                            name = "Accesos de Supervisor"
                        },
                        new
                        {
                            id = 4,
                            name = "Accesos de Coordinador"
                        },
                        new
                        {
                            id = 5,
                            name = "Accesos de Empleado"
                        });
                });

            modelBuilder.Entity("SystemBase.Models.ProfileAccess", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("canRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("canWrite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("idRole")
                        .HasColumnType("int");

                    b.Property<string>("profileTable")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("id");

                    b.HasIndex("idRole", "profileTable")
                        .IsUnique();

                    b.ToTable("profileAccess");
                });

            modelBuilder.Entity("SystemBase.Models.Roles", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("code")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("created")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("deleteAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("idNameRule")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.HasIndex("idNameRule");

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            id = 1,
                            code = 1,
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idNameRule = 1,
                            name = "CEO"
                        },
                        new
                        {
                            id = 2,
                            code = 2,
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idNameRule = 2,
                            name = "Gerente General"
                        },
                        new
                        {
                            id = 3,
                            code = 2,
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idNameRule = 2,
                            name = "Gerente RH"
                        },
                        new
                        {
                            id = 4,
                            code = 3,
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idNameRule = 3,
                            name = "Supervisor"
                        },
                        new
                        {
                            id = 5,
                            code = 4,
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idNameRule = 4,
                            name = "Coordinador"
                        },
                        new
                        {
                            id = 6,
                            code = 5,
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idNameRule = 5,
                            name = "Operador de producción"
                        },
                        new
                        {
                            id = 7,
                            code = 5,
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idNameRule = 5,
                            name = "Auxiliar de almacén"
                        },
                        new
                        {
                            id = 8,
                            code = 5,
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idNameRule = 5,
                            name = "Personal de limpieza industrial"
                        });
                });

            modelBuilder.Entity("SystemBase.Models.Team", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTimeOffset>("created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("id");

                    b.ToTable("teams");
                });

            modelBuilder.Entity("SystemBase.Models.UserAssignments", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("codeEmployee")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTimeOffset>("created")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("deleteAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("idRole")
                        .HasColumnType("int");

                    b.Property<int>("idUser")
                        .HasColumnType("int");

                    b.Property<bool>("isActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("scopeId")
                        .HasColumnType("int");

                    b.Property<string>("scopeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("id");

                    b.HasIndex("idRole");

                    b.HasIndex("idUser");

                    b.HasIndex("scopeId", "scopeType", "idUser", "idRole")
                        .IsUnique()
                        .HasFilter("[scopeId] IS NOT NULL");

                    b.ToTable("userAssignments");

                    b.HasData(
                        new
                        {
                            id = 1,
                            codeEmployee = "CEO-01",
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idRole = 1,
                            idUser = 1,
                            isActive = true,
                            scopeId = 1,
                            scopeType = "company"
                        },
                        new
                        {
                            id = 2,
                            codeEmployee = "GG-01",
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idRole = 2,
                            idUser = 2,
                            isActive = true,
                            scopeId = 1,
                            scopeType = "campus_area"
                        },
                        new
                        {
                            id = 3,
                            codeEmployee = "GG-02",
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idRole = 2,
                            idUser = 3,
                            isActive = true,
                            scopeId = 1,
                            scopeType = "campus_area"
                        },
                        new
                        {
                            id = 4,
                            codeEmployee = "GRH-01",
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idRole = 3,
                            idUser = 4,
                            isActive = true,
                            scopeId = 2,
                            scopeType = "campus_area"
                        },
                        new
                        {
                            id = 5,
                            codeEmployee = "SUP-01",
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idRole = 4,
                            idUser = 5,
                            isActive = true,
                            scopeId = 1,
                            scopeType = "campus_area_workdate"
                        },
                        new
                        {
                            id = 6,
                            codeEmployee = "SUP-02",
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idRole = 4,
                            idUser = 6,
                            isActive = true,
                            scopeId = 2,
                            scopeType = "campus_area_workdate"
                        },
                        new
                        {
                            id = 7,
                            codeEmployee = "COORD-01",
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idRole = 5,
                            idUser = 7,
                            isActive = true,
                            scopeId = 1,
                            scopeType = "team"
                        },
                        new
                        {
                            id = 8,
                            codeEmployee = "COORD-02",
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idRole = 5,
                            idUser = 8,
                            isActive = true,
                            scopeId = 2,
                            scopeType = "team"
                        },
                        new
                        {
                            id = 10,
                            codeEmployee = "OP-01",
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idRole = 6,
                            idUser = 10,
                            isActive = true,
                            scopeId = 1,
                            scopeType = "team"
                        },
                        new
                        {
                            id = 11,
                            codeEmployee = "OP-02",
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idRole = 6,
                            idUser = 11,
                            isActive = true,
                            scopeId = 1,
                            scopeType = "team"
                        },
                        new
                        {
                            id = 12,
                            codeEmployee = "ALM-01",
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idRole = 7,
                            idUser = 12,
                            isActive = true,
                            scopeId = 1,
                            scopeType = "team"
                        },
                        new
                        {
                            id = 13,
                            codeEmployee = "LIMP-01",
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idRole = 8,
                            idUser = 13,
                            isActive = true,
                            scopeId = 1,
                            scopeType = "team"
                        },
                        new
                        {
                            id = 14,
                            codeEmployee = "OP-03",
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idRole = 6,
                            idUser = 14,
                            isActive = true,
                            scopeId = 2,
                            scopeType = "team"
                        },
                        new
                        {
                            id = 15,
                            codeEmployee = "ALM-02",
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idRole = 7,
                            idUser = 15,
                            isActive = true,
                            scopeId = 2,
                            scopeType = "team"
                        },
                        new
                        {
                            id = 16,
                            codeEmployee = "ALM-03",
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idRole = 7,
                            idUser = 16,
                            isActive = true,
                            scopeId = 2,
                            scopeType = "team"
                        },
                        new
                        {
                            id = 17,
                            codeEmployee = "LIMP-02",
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idRole = 8,
                            idUser = 17,
                            isActive = true,
                            scopeId = 2,
                            scopeType = "team"
                        },
                        new
                        {
                            id = 18,
                            codeEmployee = "LIMP-03",
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idRole = 8,
                            idUser = 18,
                            isActive = true,
                            scopeId = 2,
                            scopeType = "team"
                        });
                });

            modelBuilder.Entity("SystemBase.Models.Users", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("apm")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("app")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("created")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("deleteAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("imageUser")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("id");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            id = 1,
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            name = "Lois",
                            password = "$argon2id$v=19$m=32768,t=3,p=2$1FvPw8ON7Zw6oEf2Osme6g$S10MxurrnQAxChp35pkWuKUftXMQ2JokSn0xH0NuSlo",
                            userName = "@lois"
                        },
                        new
                        {
                            id = 2,
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            name = "Hal",
                            password = "$argon2id$v=19$m=32768,t=3,p=2$1yOPpSdzIDaTLXqFkUSesA$f2wEU/tFH9cPz50AqcdhO0drbGGV6VcYyOQYOpFfef8",
                            userName = "@hal"
                        },
                        new
                        {
                            id = 3,
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            name = "Francis",
                            password = "$argon2id$v=19$m=32768,t=3,p=2$kcfywtEZQ9dDvhZqxVXC3Q$s6zCrp1joQt2lNZL24jIv7HuZ1pQyqQyHJgajlFM3Rs",
                            userName = "@francis"
                        },
                        new
                        {
                            id = 4,
                            app = "Feldspar",
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            name = "Craig",
                            password = "$argon2id$v=19$m=32768,t=3,p=2$iZCvmKBF+N23o7dif5KdcQ$rssv1RehIM3emOoHegIDCallne5ZVNPkeaEKnME78XM",
                            userName = "@craig"
                        },
                        new
                        {
                            id = 5,
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            name = "Malcolm",
                            password = "$argon2id$v=19$m=32768,t=3,p=2$NbPmbVmQk+B5cmEdTaLLKA$Cfde81ySo+Fi1cbfUTv8o0v4mN+dm0z4/ODGUQFo8kU",
                            userName = "@malcolm"
                        },
                        new
                        {
                            id = 6,
                            app = "Kenarban",
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            name = "Stevie",
                            password = "$argon2id$v=19$m=32768,t=3,p=2$JnnKbyY7Fi9qdGpFIO2yDA$sKb3qRl7b6YDdh9B+N3LKUUcYBJWDfaiZy+DmeMdqSw",
                            userName = "@stevie"
                        },
                        new
                        {
                            id = 7,
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            name = "Reese",
                            password = "$argon2id$v=19$m=32768,t=3,p=2$pY5FCVLVNSIhk4acOZ4V8w$4ddVT22xCanWSR7mCjh+4uGnkNqshv3EubGVmkRg248",
                            userName = "@reese"
                        },
                        new
                        {
                            id = 8,
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            name = "Dewey",
                            password = "$argon2id$v=19$m=32768,t=3,p=2$bkOakmrrx2hnCqxQWDfN1g$hAFKm2j0Dwf8OaSXSOwQyB8dRtt6m9NSdy5mQ37PVxs",
                            userName = "@dewey"
                        },
                        new
                        {
                            id = 10,
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            name = "Lloyd",
                            password = "$argon2id$v=19$m=32768,t=3,p=2$knOA4LobyZ+bxKXxDyq0Xw$nHHQjcGt4eaN72rzwSGOBHFGCEgzsHN46EFYYacw18A",
                            userName = "@lloyd"
                        },
                        new
                        {
                            id = 11,
                            app = "Hooper",
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            name = "Dabney",
                            password = "$argon2id$v=19$m=32768,t=3,p=2$/auhh6xc6Xbq/ZNXrJzFBQ$1STtJl4++dkBZyMqpXDFKTuZXO0CAQdyjcryMI8duaM",
                            userName = "@dabney"
                        },
                        new
                        {
                            id = 12,
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            name = "Kevin",
                            password = "$argon2id$v=19$m=32768,t=3,p=2$H9I+8sKxKsQBWLHF/2MIIw$FJn6h2ScD5ehfMryLrY8Mi8xFy1QXLCu48c2wrSnVW4",
                            userName = "@kevin"
                        },
                        new
                        {
                            id = 13,
                            app = "Sanders",
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            name = "Cynthia",
                            password = "$argon2id$v=19$m=32768,t=3,p=2$g9+R2dct4ckuMY7WnhBEJA$bmgTBygFvfKDu+X1r0N08iJGKKWIw7lHAGwnmFsq1Ho",
                            userName = "@cynthia"
                        },
                        new
                        {
                            id = 14,
                            app = "Hanson",
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            name = "David",
                            password = "$argon2id$v=19$m=32768,t=3,p=2$4bafBEWt0V51JKORjCAaxg$10qJIN7Q1jX0c5k2LyahEItvQMzEwTg5physsmWoKHA",
                            userName = "@davidh"
                        },
                        new
                        {
                            id = 15,
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            name = "Chad",
                            password = "$argon2id$v=19$m=32768,t=3,p=2$1TDturuA2wMhUDVj82dBKQ$HSeVVMkY2b0KNSfj7HnjAFGap3gnJ/tbvETFoO8uHHM",
                            userName = "@chad"
                        },
                        new
                        {
                            id = 16,
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            name = "Davey",
                            password = "$argon2id$v=19$m=32768,t=3,p=2$kGI95T7smoyrHLYiZjxJpA$VlQJb1caD4xXPgoRbogB/wk28j9+ecL/A4vSegRop2k",
                            userName = "@davey"
                        },
                        new
                        {
                            id = 17,
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            name = "Zoe",
                            password = "$argon2id$v=19$m=32768,t=3,p=2$BzDGQzOB3gC9o2KU4jjhyA$3rKqlYVHTPi/oPnL/MkMdD7h0TYqDypZgphK9TxWZPg",
                            userName = "@zoe"
                        },
                        new
                        {
                            id = 18,
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            name = "Penelope",
                            password = "$argon2id$v=19$m=32768,t=3,p=2$wHllPmLdda3b0WSDSVkDRA$pcUwsI88YhXUnFZapcSFviEEUmWjKsINSLPKw4LaOEY",
                            userName = "@penelope"
                        });
                });

            modelBuilder.Entity("SystemBase.Models.WorkShift", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTimeOffset>("created")
                        .HasColumnType("datetimeoffset");

                    b.Property<TimeOnly>("hourEnd")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("hourInit")
                        .HasColumnType("time");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("id");

                    b.ToTable("workShifts");
                });

            modelBuilder.Entity("SystemBase.Models.endpointAccess", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTimeOffset?>("deleteAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("endpoint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("method")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("permission")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.ToTable("endpointAccess");

                    b.HasData(
                        new
                        {
                            id = 1,
                            endpoint = "/auth/logout",
                            method = "POST",
                            permission = "auth.logout.*",
                            status = true
                        },
                        new
                        {
                            id = 2,
                            endpoint = "/auth/logout",
                            method = "POST",
                            permission = "auth.logout.subordinate",
                            status = true
                        },
                        new
                        {
                            id = 3,
                            endpoint = "/auth/access",
                            method = "GET",
                            permission = "auth.access.*",
                            status = true
                        },
                        new
                        {
                            id = 4,
                            endpoint = "/auth/access",
                            method = "GET",
                            permission = "auth.access.subordinate",
                            status = true
                        },
                        new
                        {
                            id = 5,
                            endpoint = "/user",
                            method = "GET",
                            permission = "users.read.self",
                            status = true
                        },
                        new
                        {
                            id = 6,
                            endpoint = "/user",
                            method = "GET",
                            permission = "users.read.*",
                            status = true
                        },
                        new
                        {
                            id = 7,
                            endpoint = "/user",
                            method = "GET",
                            permission = "users.read.subordinate",
                            status = true
                        },
                        new
                        {
                            id = 8,
                            endpoint = "/user/{id}",
                            method = "GET",
                            permission = "users.read.self",
                            status = true
                        },
                        new
                        {
                            id = 9,
                            endpoint = "/user/{id}",
                            method = "GET",
                            permission = "users.read.subordinate",
                            status = true
                        },
                        new
                        {
                            id = 10,
                            endpoint = "/user/{id}",
                            method = "GET",
                            permission = "users.read.*",
                            status = true
                        },
                        new
                        {
                            id = 11,
                            endpoint = "/user",
                            method = "POST",
                            permission = "users.create.*",
                            status = true
                        },
                        new
                        {
                            id = 12,
                            endpoint = "/user/{id}",
                            method = "PUT",
                            permission = "users.update.self",
                            status = true
                        },
                        new
                        {
                            id = 13,
                            endpoint = "/user/{id}",
                            method = "PUT",
                            permission = "users.update.subordinate",
                            status = true
                        },
                        new
                        {
                            id = 14,
                            endpoint = "/user/{id}",
                            method = "PUT",
                            permission = "users.update.*",
                            status = true
                        },
                        new
                        {
                            id = 15,
                            endpoint = "/user/{id}",
                            method = "DELETE",
                            permission = "users.delete.*",
                            status = true
                        },
                        new
                        {
                            id = 16,
                            endpoint = "/user/{id}/status",
                            method = "PATCH",
                            permission = "users.status.*",
                            status = true
                        },
                        new
                        {
                            id = 17,
                            endpoint = "/user/{id}/assignment",
                            method = "POST",
                            permission = "users.assignment.create.*",
                            status = true
                        },
                        new
                        {
                            id = 18,
                            endpoint = "/user/{id}/assignment/{assignmentId}",
                            method = "DELETE",
                            permission = "users.assignment.delete.*",
                            status = true
                        },
                        new
                        {
                            id = 19,
                            endpoint = "/user/{id}/password",
                            method = "PUT",
                            permission = "users.password.self",
                            status = true
                        },
                        new
                        {
                            id = 20,
                            endpoint = "/user/{id}/password",
                            method = "PUT",
                            permission = "users.password.*",
                            status = true
                        },
                        new
                        {
                            id = 21,
                            endpoint = "/user/{id}/assignments",
                            method = "GET",
                            permission = "users.assignment.read.self",
                            status = true
                        },
                        new
                        {
                            id = 22,
                            endpoint = "/user/{id}/assignments",
                            method = "GET",
                            permission = "users.assignment.read.subordinate",
                            status = true
                        },
                        new
                        {
                            id = 23,
                            endpoint = "/user/{id}/assignments",
                            method = "GET",
                            permission = "users.assignment.read.*",
                            status = true
                        },
                        new
                        {
                            id = 24,
                            endpoint = "/auth/logout",
                            method = "POST",
                            permission = "auth.logout.self",
                            status = true
                        },
                        new
                        {
                            id = 25,
                            endpoint = "/auth/access",
                            method = "GET",
                            permission = "auth.access.self",
                            status = true
                        });
                });

            modelBuilder.Entity("SystemBase.Models.refreshTokens", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTimeOffset>("SessionExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("agentUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("createdAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("expiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("idUser")
                        .HasColumnType("int");

                    b.Property<string>("ipAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("tokenHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("idUser");

                    b.ToTable("refreshTokens");
                });

            modelBuilder.Entity("SystemBase.Models.Campus", b =>
                {
                    b.HasOne("SystemBase.Models.Company", "company")
                        .WithMany()
                        .HasForeignKey("idCompany")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("company");
                });

            modelBuilder.Entity("SystemBase.Models.CampusArea", b =>
                {
                    b.HasOne("SystemBase.Models.Area", "area")
                        .WithMany()
                        .HasForeignKey("idArea")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SystemBase.Models.Campus", "campus")
                        .WithMany()
                        .HasForeignKey("idCampus")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("area");

                    b.Navigation("campus");
                });

            modelBuilder.Entity("SystemBase.Models.CampusAreaWorkShift", b =>
                {
                    b.HasOne("SystemBase.Models.CampusArea", "campusArea")
                        .WithMany()
                        .HasForeignKey("idCampusArea")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SystemBase.Models.WorkShift", "workShift")
                        .WithMany()
                        .HasForeignKey("idWorkShift")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("campusArea");

                    b.Navigation("workShift");
                });

            modelBuilder.Entity("SystemBase.Models.CampusAreaWorkShiftTeam", b =>
                {
                    b.HasOne("SystemBase.Models.CampusAreaWorkShift", "campusAreaWorkShift")
                        .WithMany()
                        .HasForeignKey("idCampusAreaWorkShift")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SystemBase.Models.Team", "team")
                        .WithMany()
                        .HasForeignKey("idTeam")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("campusAreaWorkShift");

                    b.Navigation("team");
                });

            modelBuilder.Entity("SystemBase.Models.EndpointAccessNameRule", b =>
                {
                    b.HasOne("SystemBase.Models.endpointAccess", "endpointAccess")
                        .WithMany("endpointAccessNameRules")
                        .HasForeignKey("idEndpointAccess")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SystemBase.Models.NameRule", "nameRule")
                        .WithMany("endpointAccessNameRules")
                        .HasForeignKey("idNameRule")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("endpointAccess");

                    b.Navigation("nameRule");
                });

            modelBuilder.Entity("SystemBase.Models.ProfileAccess", b =>
                {
                    b.HasOne("SystemBase.Models.Roles", "roles")
                        .WithMany()
                        .HasForeignKey("idRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("roles");
                });

            modelBuilder.Entity("SystemBase.Models.Roles", b =>
                {
                    b.HasOne("SystemBase.Models.NameRule", "nameRule")
                        .WithMany("roles")
                        .HasForeignKey("idNameRule");

                    b.Navigation("nameRule");
                });

            modelBuilder.Entity("SystemBase.Models.UserAssignments", b =>
                {
                    b.HasOne("SystemBase.Models.Roles", "roles")
                        .WithMany()
                        .HasForeignKey("idRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SystemBase.Models.Users", "users")
                        .WithMany()
                        .HasForeignKey("idUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("roles");

                    b.Navigation("users");
                });

            modelBuilder.Entity("SystemBase.Models.refreshTokens", b =>
                {
                    b.HasOne("SystemBase.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("idUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SystemBase.Models.NameRule", b =>
                {
                    b.Navigation("endpointAccessNameRules");

                    b.Navigation("roles");
                });

            modelBuilder.Entity("SystemBase.Models.endpointAccess", b =>
                {
                    b.Navigation("endpointAccessNameRules");
                });
#pragma warning restore 612, 618
        }
    }
}
