// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SystemBase.Data;

#nullable disable

namespace SystemBase.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    [Migration("20260330175611_Reestructuracion de Base de datos")]
    partial class ReestructuraciondeBasededatos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SystemBase.Models.EndpointAccessNameRule", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("idEndpointAccess")
                        .HasColumnType("int");

                    b.Property<int>("idNameRule")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("idEndpointAccess");

                    b.HasIndex("idNameRule");

                    b.ToTable("endpointAccessNameRules");

                    b.HasData(
                        new
                        {
                            id = 1,
                            idEndpointAccess = 1,
                            idNameRule = 1
                        },
                        new
                        {
                            id = 2,
                            idEndpointAccess = 3,
                            idNameRule = 1
                        },
                        new
                        {
                            id = 3,
                            idEndpointAccess = 6,
                            idNameRule = 1
                        });
                });

            modelBuilder.Entity("SystemBase.Models.NameRule", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.ToTable("nameRules");

                    b.HasData(
                        new
                        {
                            id = 1,
                            name = "Acceso de CEO"
                        },
                        new
                        {
                            id = 2,
                            name = "Accesos de Gerente N-1"
                        });
                });

            modelBuilder.Entity("SystemBase.Models.Roles", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("code")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("created")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("idNameRule")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.HasIndex("idNameRule");

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            id = 1,
                            code = 1,
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idNameRule = 1,
                            name = "CEO"
                        },
                        new
                        {
                            id = 2,
                            code = 2,
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            name = "Gerente de Nave"
                        });
                });

            modelBuilder.Entity("SystemBase.Models.UserAssignments", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("codeEmployee")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTimeOffset>("created")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("idRole")
                        .HasColumnType("int");

                    b.Property<int>("idUser")
                        .HasColumnType("int");

                    b.Property<bool>("isActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("scopeId")
                        .HasColumnType("int");

                    b.Property<string>("scopeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("id");

                    b.HasIndex("idRole");

                    b.HasIndex("idUser");

                    b.HasIndex("scopeId", "scopeType", "idUser", "idRole")
                        .IsUnique()
                        .HasFilter("[scopeId] IS NOT NULL");

                    b.ToTable("userAssignments");

                    b.HasData(
                        new
                        {
                            id = 1,
                            codeEmployee = "N1-12",
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            idRole = 1,
                            idUser = 1,
                            isActive = true,
                            scopeType = "COMPANY"
                        });
                });

            modelBuilder.Entity("SystemBase.Models.Users", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("apm")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("app")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("imageUser")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("id");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            id = 1,
                            apm = "Mendez",
                            app = "Diaz",
                            created = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            name = "Jhonatan",
                            password = "$argon2id$v=19$m=32768,t=3,p=2$bhkcNveySO7GCFRIplR10g$3bIVoeiWRchUxJjRwIF2mteIepZzTzc/6VhhOhMcvV4",
                            userName = "@adminDev"
                        });
                });

            modelBuilder.Entity("SystemBase.Models.endpointAccess", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("endpoint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("method")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("permission")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.ToTable("endpointAccess");

                    b.HasData(
                        new
                        {
                            id = 1,
                            endpoint = "/auth/logout",
                            method = "POST",
                            permission = "auth.logout.*",
                            status = true
                        },
                        new
                        {
                            id = 2,
                            endpoint = "/auth/logout",
                            method = "POST",
                            permission = "auth.logout.subordinate",
                            status = true
                        },
                        new
                        {
                            id = 3,
                            endpoint = "/auth/access",
                            method = "GET",
                            permission = "auth.access.*",
                            status = true
                        },
                        new
                        {
                            id = 4,
                            endpoint = "/auth/access",
                            method = "GET",
                            permission = "auth.access.subordinate",
                            status = true
                        },
                        new
                        {
                            id = 5,
                            endpoint = "/user",
                            method = "GET",
                            permission = "users.read.self",
                            status = true
                        },
                        new
                        {
                            id = 6,
                            endpoint = "/user",
                            method = "GET",
                            permission = "users.read.*",
                            status = true
                        },
                        new
                        {
                            id = 7,
                            endpoint = "/user",
                            method = "GET",
                            permission = "user.read.subordinate",
                            status = true
                        });
                });

            modelBuilder.Entity("SystemBase.Models.refreshTokens", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTimeOffset>("SessionExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("agentUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("createdAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("expiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("idUser")
                        .HasColumnType("int");

                    b.Property<string>("ipAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("tokenHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("idUser");

                    b.ToTable("refreshTokens");
                });

            modelBuilder.Entity("SystemBase.Models.EndpointAccessNameRule", b =>
                {
                    b.HasOne("SystemBase.Models.endpointAccess", "endpointAccess")
                        .WithMany("endpointAccessNameRules")
                        .HasForeignKey("idEndpointAccess")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SystemBase.Models.NameRule", "nameRule")
                        .WithMany("endpointAccessNameRules")
                        .HasForeignKey("idNameRule")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("endpointAccess");

                    b.Navigation("nameRule");
                });

            modelBuilder.Entity("SystemBase.Models.Roles", b =>
                {
                    b.HasOne("SystemBase.Models.NameRule", "nameRule")
                        .WithMany("roles")
                        .HasForeignKey("idNameRule");

                    b.Navigation("nameRule");
                });

            modelBuilder.Entity("SystemBase.Models.UserAssignments", b =>
                {
                    b.HasOne("SystemBase.Models.Roles", "roles")
                        .WithMany()
                        .HasForeignKey("idRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SystemBase.Models.Users", "users")
                        .WithMany()
                        .HasForeignKey("idUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("roles");

                    b.Navigation("users");
                });

            modelBuilder.Entity("SystemBase.Models.refreshTokens", b =>
                {
                    b.HasOne("SystemBase.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("idUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SystemBase.Models.NameRule", b =>
                {
                    b.Navigation("endpointAccessNameRules");

                    b.Navigation("roles");
                });

            modelBuilder.Entity("SystemBase.Models.endpointAccess", b =>
                {
                    b.Navigation("endpointAccessNameRules");
                });
#pragma warning restore 612, 618
        }
    }
}
